### PR TITLE
Support for Python 3.6

### PR DESCRIPTION
**Pull request by vikas5914**
This PR fix some the issue with python 3.6

In Python 3,
1) import syntax has been changed [PEP404](https://www.python.org/dev/peps/pep-0404/#imports).
2) ConfigParser has been renamed to configparser for PEP 8 compliance 

Also fix the join() function.

### CODE REVIEW

**Comment by splewis** [comment]
Thanks!

**Comment by vikas5914** [comment]
Hi, 

When i run smbuilder . This is the output. 

`spcomp ././scripting/retakes_standardallocator.sp  -o=./builds/plugins/retakes_standardallocator -e=./builds/plugins/retakes_standardallocator.txt`

If you notice, there is `././` in first argument. how can i make it only single `./` like `./scripting`

**Comment by splewis** [comment]
I don't know how you can change that. 

I may need to roll this change back - it's breaking my current travis builds for sm plugins that clone sm-builder in the travis config. I haven't fully investigated to see what I can do about it, though.

**Comment by vikas5914** [comment]
I found the problem. 

travis is using python 2 for your project.  and that's why it's not finding the configparser package. (in python3 is its lowercase).

If I fore travis to use Python 3, for some reason it can not find smbuilder.builder

Right now, revert back this merge. I will look into it more.

**Pull request merged**
